global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'flask'
    static_configs:
      - targets: ['api:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
